slides.latexmk: 
	latexmk -pvc -pdf -pdflatex='pdflatex -halt-on-error'  slides.tex --view=none

clean:
	rm slides.aux slides.bbl slides.blg slides.log slides.out slides.pdf slides.fls slides.nav slides.snm slides.toc


